[package]
name = "day05"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gcollections = "1.5.0"
intervallum = "1.4.0"
itertools = "0.12.0"
